version: "2"
services:

  web:
    build:
      context: .
      dockerfile: container-build/web/Dockerfile
    environment:
      - MYSQL_DATABASE=docker_zf3
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local
      - MYSQL_HOST=db
    ports:
      - "8080:80"
      - "8089:8089"
    volumes:
      - .:/var/www
      - ./container-build/web/upload.ini:/usr/local/etc/php/conf.d/upload.ini
    depends_on:
      - db

  db:
    image: mariadb:latest
    ports:
      - "2202:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=local
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local
      - MYSQL_DATABASE=docker_zf3
    volumes:
      - "mysql_data:/var/lib/mysql"
      - ./container-build/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: { driver: local }
