<?php
$form = $this->form;
//$form->get('author')->setAttributes([
//    'class' => 'form-control',
//    'placeholder' => 'Author\'s name'
//]);

$form->get('comment')->setAttributes([
    'class' => 'form-control',
    'rows' => 6,
    'placeholder' => 'Text'
]);

$form->get('submit')->setAttributes(['class' => 'bun btn-primary']);
$form->prepare();

?>
<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Post View</span></h1>
</div>

<a href="
    <?= $this->url('application', ['action' => 'index']); ?>">
    &lt;&lt; Back to list of posts
</a>
<h1>
    <?= $this->escapeHtml($post->getTitle()); ?>
</h1>

<p class="comments-header">
    <?= $this->escapeHtml($postManager->getCommentCountStr($post)); ?> |
    <a href="#comment">
        Add new comment
    </a>
</p>

<p>
    Published: <?= $this->escapeHtml(date('jS \of F Y', strtotime($post->getDateCreated()))); ?> by: <?= $post->getAuthor()->getName()?>
    | Tags: <?= $this->escapeHtml($postManager->convertTagsToString($post)); ?>
</p>
<p>
    <?= $this->escapeHtml($post->getContent()); ?>
</p>

<h3><?= $this->escapeHtml($postManager->getCommentCountStr($post)); ?></h3>

<?php if ($post->getComments()): foreach ($post->getComments() as $comment): ?>

    <hr>

    <p>
        <?= $this->escapeHtml($comment->getAuthor()->getName()) ?> on
        <?= $this->escapeHtml($comment->getDateCreated()); ?>
    </p>

    <p>
        <?= $this->escapeHtml($comment->getContent()); ?>
    </p>

<?php endforeach; endif; ?>

<hr>

<a name="comment"></a>
<h3>Leave Reply</h3>

<div class="row">
    <div class="col-md-8">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('comment')); ?>
            <?= $this->formElement($form->get('comment')); ?>
            <?= $this->formElementErrors($form->get('comment')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
